server:
  port: 8887
spring:
  application:
    name: aop-microservice-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jianghaisen/aop-microservice.git
          search-paths: aop-microservice-config-repo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/